pipeline {
    agent{
        docker {
            image 'node'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = true
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm install http-server -g'
            }
        }
        stage('Test') {
            steps {
               sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deploy') {
            steps {
               sh './jenkins/scripts/deploy.sh'
            }
        }
    }
}
