pipeline {
    agent{
        docker {
            image 'node'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = true
    }
    stages {
        stage('Install http-server') {
            steps {
                sh 'npm install http-server -g'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
               sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deploy') {
            steps {
               sh './jenkins/scripts/deploy.sh'
               input message: 'Finished using the website? (Click "Proceed" to continue)'
               sh './jenkins/scripts/kill.sh'
            }
        }
    }
}